package com.example.bipapp.client;


public enum ETypePacket {
    SIGN_IN,
    SIGN_UP,

    GET_ALL_SKILLS,
    GET_USER_INFO,
    CHANGE_USER_INFO,

    GET_ALL_PROJECT_TAGS,
    CREATE_PROJECT,
    UPDATE_PROJECT,
    DELETE_PROJECT,
    SEARCH_PROJECTS,

    SUBSCRIBE_PROJECT,
    UNSUBSCRIBE_PROJECT,
    ACCEPT_VOLUNTEER,
    DELETE_VOLUNTEER,
    LEAVE_PROJECT,
    DELETE_PARTICIPANT,

    GET_SUBSCRIBERS,
    ACCEPT_SUBSCRIBER,
    DELETE_SUBSCRIBER,
    UNSUBSCRIBE_SUBSCRIPTION,

    TMP,
    BAD;
}
